server:
  port: 8887

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.board_was.model

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    jdbc.sqlonly: INFO
    jdbc.sqltiming: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: OFF
    jdbc.audit: OFF
    jdbc.connection: OFF
