server:
  port: 8887

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.board_was.model

logging.level:
  org.hibernate.SQL: debug  # logger를 통해 하이버네이트 실행 SQL
